In [3]:
import numpy as np

x = np.arange(1,21).reshape(4,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [5]:
y = x[:3 , 2:]
print(y)

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [13]:
y = x[2,:]
print(y)

[11 12 13 14 15]


In [12]:
z = x[:,2] 
print(z)

[ 3  8 13 18]


In [15]:
z = np.diag(x,k=-1)
print(z)

[ 6 12 18]
